# Generated by Django 6.0 on 2026-01-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('with_driver', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Модель автомобиля')),
                ('photo', models.ImageField(upload_to='cars/%Y/%m/%d/', verbose_name='Главное фото')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('car_type', models.CharField(choices=[('electric', 'Электромобиль'), ('premium', 'Премиум'), ('suv', 'Кроссовер / SUV'), ('cargo', 'Грузовой / Минивэн')], max_length=20, verbose_name='Класс автомобиля')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки')),
                ('seats', models.PositiveSmallIntegerField(default=5, verbose_name='Количество мест')),
                ('luggage', models.CharField(blank=True, max_length=100, verbose_name='Объём багажника (примерно)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для брони')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['name'],
            },
        ),
    ]
